import MinRouter from "MinRouter.js"
const router = new MinRouter({
	routes:[
		{
			path:'pages/tab1',
			type: 'navigateTo',
			name:'tab1'
		},
		{
			path:'pages/tab2',
			name:'tab2'
		},
		{
			path:'pages/tab3',
			name:'tab3'
		},
		{
			path:'pages/tab4',
			name:'tab4'
		},
		{
			path:'pages/common/login',
			name:'login'
		},
		{
			path:'pages/tab1/searchGood',
			name:'searchGood'
		},
		{
			path:'pages/common/service',
			name:'service'
		},
		{
			path:'pages/tab1/recommendVideo',
			name:'recommendVideo'
		},
		{
			path:'pages/common/shopGoodInfo',
			name:'shopGoodInfo'
		},
		{
			path:'pages/tab1/searchdrawingGood',
			name:'searchdrawingGood'
		},
		{
			path:'pages/common/confirmOrder',
			name:'confirmOrder'
		},
		{
			path:'pages/common/shopSelectAddress',
			name:'shopSelectAddress'
		},
		{
			path:'pages/common/shopReceiveAddress',
			name:'shopReceiveAddress'
		},
		{
			path:"pages/tab4/setting",
			name:'setting'
		},
		{
			path:"pages/tab4/drawbalanceRecord",
			name:"drawbalanceRecord"
		},
		{
			path:"pages/tab4/earningsDetail",
			name:"earningsDetail"
		},
		{
			path:"pages/tab4/drawBalance",
			name:"drawBalance"
		},
		{
			path:"pages/tab4/drawbalanceExplain",
			name:'drawbalanceExplain'
		},
		{
			path:'pages/tab4/order',
			name:'order'
		},
		{
			path:'pages/tab4/orderEvaluate',
			name:'orderEvaluate'
		},
		{
			path:"pages/tab4/orderInfo",
			name:'orderInfo'
		},
		{
			path:"pages/tab4/myTeam",
			name:'myTeam'
		},
		{
			path:'pages/tab4/myCode',
			name:'myCode'
		},
		{
			path:'pages/tab4/myCodept',
			name:'myCodept'
		},
		{
			path:'pages/tab4/management',
			name:'management'
		},
		{
			path:'pages/tab4/managementZdDsz',
			name:'managementZdDsz'
		},
		{
			path:'pages/tab4/managementGoodinfo',
			name:'managementGoodinfo'
		},
		{
			path:'pages/tab4/managementGoodinfoZdDsz',
			name:'managementGoodinfoZdDsz'
		},
		{
			path:'pages/tab4/managementAddgood',
			name:'managementAddgood'
		},
		{
			path:'pages/tab4/managementEditgood',
			name:'managementEditgood'
		},
		{
			path:'pages/tab4/managementClassifygood',
			name:'managementClassifygood'
		},
		{
			path:'pages/tab4/managementCarriage',
			name:'managementCarriage'
		},
		{
			path:'pages/tab4/managementAddgoodimg',
			name:'managementAddgoodimg'
		},
		{
			path:'pages/tab4/managementSpecification',
			name:'managementSpecification'
		},
		{
			path:'pages/tab4/managementAddSizer',
			name:'managementAddSizer'
		},
		{
			path:'pages/common/bindMobile',
			name:'bindMobile'
		},
		{
			path:'pages/common/shopGoodEvaluatelist',
			name:'shopGoodEvaluatelist'
		},
		{
			path:"pages/common/articleInfo",
			name:'articleInfo'
		},
		{
			path:'pages/common/webView',
			name:'webView'
		},
		{
			path:'pages/common/scanCode',
			name:'scanCode'
		},
		{
			path:'pages/tab4/officialAccounts',
			name:'officialAccounts'
		},
		{
			path:'pages/tab4/bindAliPay',
			name:'bindAliPay'
		},
		{
			path:'pages/common/systemGoodEvaluatelist',
			name:'systemGoodEvaluatelist'
		},
		{
			path:'pages/tab4/teamOrder',
			name:'teamOrder'
		},
		{
			path:'pages/tab4/teamTodayOrder',
			name:'teamTodayOrder'
		},
		{
			path:"pages/tab4/integralRecord",
			name:'integralRecord'
		},
		{
			path:"pages/tab1/integralShop",
			name:'integralShop'
		},
		{
			path:"pages/tab1/integralDetail",
			name:'integralDetail'
		},
		{
			path:'pages/tab1/integralOrder',
			name:'integralOrder'
		},
		{
			path:'pages/tab1/newTimeTab',
			name:'newTimeTab'
		},
	]
})

export default router;